### ISSUE TITLE
Can't run on macos 

### ISSUE THREAD

**Issue by okanduzyel** [zassou65535/WaveGAN#1]
Hi, 

I cloned your code correctly, installed all requirements, and tried to run with python WaveGAN_inference.py but It doesn't run. 

```
(base) okanduzyel@Okan-MacBook-Pro wavegan % python WaveGAN_inference.py
Traceback (most recent call last):
  File "/Users/okanduzyel/Downloads/WaveGAN/WaveGAN_inference.py", line 3, in <module>
    from module.importer import *
  File "/Users/okanduzyel/Downloads/WaveGAN/module/importer.py", line 18, in <module>
    import torchvision
ModuleNotFoundError: No module named 'torchvision'
```

By the way, please add an English explanation on the readme.

**Comment by zassou65535** [comment]
I assumed linux, not macOS. I'm Sorry for the lack of explanation. I'll add explanation about it on the readme.
Thank you for your interest on my code and pointing that out.
